# Generated by Django 5.2.7 on 2025-11-02 20:33

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(default='pl', max_length=8)),
                ('content', models.TextField(validators=[django.core.validators.MinLengthValidator(2500), django.core.validators.MaxLengthValidator(5000)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'place_descriptions',
                'ordering': ['route_point'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tags',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('osm_id', models.BigIntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('wikipedia_id', models.TextField(blank=True, db_index=True, null=True, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('lat', models.FloatField(validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('lon', models.FloatField(validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('data', models.JSONField(blank=True, help_text='Additional data from OSM/Wikipedia', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'places',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['lat', 'lon'], name='places_idx_lat_lon')],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('status', models.CharField(choices=[('temporary', 'Temporary'), ('saved', 'Saved')], db_index=True, max_length=20)),
                ('route_type', models.CharField(choices=[('ai_generated', 'AI Generated'), ('manual', 'Manual')], max_length=20)),
                ('saved_at', models.DateTimeField(blank=True, null=True)),
                ('cached_at', models.DateTimeField(blank=True, null=True)),
                ('cache_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'routes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_type', models.CharField(choices=[('place_description', 'Place Description'), ('route', 'Route')], max_length=20)),
                ('rating_value', models.SmallIntegerField(choices=[(-1, 'Downvote'), (1, 'Upvote')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('place_description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='core.placedescription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='core.route')),
            ],
            options={
                'db_table': 'ratings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIGenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.TextField()),
                ('provider', models.TextField(blank=True, null=True)),
                ('prompt_hash', models.TextField(blank=True, null=True)),
                ('tags_snapshot', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, help_text='Tags at time of generation', size=None)),
                ('additional_text_snapshot', models.TextField(blank=True, null=True)),
                ('points_count', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)])),
                ('tokens_prompt', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('tokens_completion', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('cost_usd', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('request_id', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_logs', to='core.route')),
            ],
            options={
                'db_table': 'ai_generation_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoutePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('ai_generated', 'AI Generated'), ('manual', 'Manual')], max_length=20)),
                ('position', models.IntegerField(help_text='Base position in route')),
                ('optimized_position', models.IntegerField(blank=True, help_text='Position after optimization', null=True)),
                ('is_removed', models.BooleanField(db_index=True, default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_points', to='core.place')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='core.route')),
            ],
            options={
                'db_table': 'route_points',
                'ordering': ['route', 'position'],
            },
        ),
        migrations.AddField(
            model_name='placedescription',
            name='route_point',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='description', to='core.routepoint'),
        ),
        migrations.CreateModel(
            name='RouteTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_tags', to='core.route')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='route_tags', to='core.tag')),
            ],
            options={
                'db_table': 'route_tags',
            },
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['user', 'status', '-created_at'], name='routes_idx_usr_stat_cr'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['route_type'], name='routes_idx_type'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['user'], name='ratings_idx_user'),
        ),
        migrations.AddIndex(
            model_name='aigenerationlog',
            index=models.Index(fields=['route', '-created_at'], name='ai_log_idx_route_created'),
        ),
        migrations.AddIndex(
            model_name='routepoint',
            index=models.Index(fields=['route', 'position'], name='rp_idx_route_pos'),
        ),
        migrations.AddIndex(
            model_name='routepoint',
            index=models.Index(fields=['route', 'is_removed'], name='rp_idx_route_removed'),
        ),
        migrations.AddIndex(
            model_name='routetag',
            index=models.Index(fields=['tag'], name='route_tags_idx_tag'),
        ),
        migrations.AlterUniqueTogether(
            name='routetag',
            unique_together={('route', 'tag')},
        ),
    ]
